### ISSUE TITLE
how to run it on ubuntu?

### ISSUE THREAD

**Issue by Koora7334** [Nicolas62x/UDPShield#1]
Hello,
I was wondering how I can run it on Linux?
Do I need to use mono?
Thanks

**Comment by Nicolas62x** [comment]
Hello !
No you don't need mono for newer .Net projects, this one only requires the .Net5 runtime to run.

V1 release has:
- .Net5.0 executables that requires the .Net5 runtime to be installed
- Standalones releases that are heavier but should run without the runtime installed

I will create a V1.1 using the latest .Net release since .Net 5 i kind of outdated now.
